### PR TITLE
Fix dict snapshot

### LINKED ISSUE #723: Returning snapshot of dict causes double free
```
fn main() -> @Felt252Dict<u32> {
    let mut dict: Felt252Dict<u32> = Default::default();
                dict.insert(2, 1_u32);

    @dict
}
```

```
free(): double free detected in tcache 2
Aborted
```

I think we should also handle `snapshot_take` for dicts

### PR DESCRIPTION
**Pull request by edg-l**
Also frees the allocated dict values, beforehand they werent and probs leaked.

Fixes #723 

## Checklist
- [ ] Linked to Github Issue
- [ ] Unit tests added
- [ ] Integration tests added.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

### CODE REVIEW

File: src/types/felt252_dict.rs [hunk 1]
```diff
@@ -28,22 +34,79 @@ pub fn build<'ctx>(
...
+    _registry: &ProgramRegistry<CoreType, CoreLibfunc>,
+    entry: &'this Block<'ctx>,
+    location: Location<'ctx>,
+    helper: &LibfuncHelper<'ctx, 'this>,
+    metadata: &mut MetadataStorage,
+    _info: WithSelf<InfoAndTypeConcreteType>,
+    src_value: Value<'ctx, 'this>,
+) -> Result<(&'this Block<'ctx>, Value<'ctx, 'this>)> {
+    // This snapshot take assumes the value types in a felt are always copy and don't need deep cloning.
+    // So far (atleast up to 2.6.4) you cannot make a felt dict of array values, so this holds.
```
Comment (juanbono) [inline src/types/felt252_dict.rs:66]: and what about structs?

Comment (juanbono) [reply src/types/felt252_dict.rs:66]: it can hold arbitrary types via a Nullable<T> value. So if we have a struct `A` (or an array, another dict, etc), `FeltDict252<Nullable<A>>` is valid.

**Review by juanbono — CHANGES_REQUESTED** [review]

**Comment by edg-l** [comment]
Converted to draft as its missing this use case

```
fn main() -> @Felt252Dict<Nullable<Array<u32>>> {
    let mut dict: Felt252Dict<Nullable<Array<u32>>> = Default::default();
    dict.insert(2, NullableTrait::new(array![0]));

    @dict
}
```

File: src/types/felt252_dict.rs (hunk 1 above)
Comment (Oppen) [reply src/types/felt252_dict.rs:66]: This comment contradicts the findings in #723. Indeed, you can create and take snapshots from a `DictFelt<Array<Felt>>`.

**Review by juanbono — APPROVED** [review]

**Review by azteca1998 — APPROVED** [review]
