### PR TITLE
Fix Nullable<T> snapshot segfault

### LINKED ISSUE #719: nullable snapshot_take is incorrectly implemented
Example program segfaulting

```
use core::array::ArrayTrait;
use core::NullableTrait;

fn main() -> @Nullable<Array<felt252>> {
    let mut x = NullableTrait::new(array![1, 2, 3]);
    let x_s = @x;

    let mut y = NullableTrait::deref(x);
    y.append(4);

    x_s
}
```

Working on this here https://github.com/lambdaclass/cairo_native/pull/718

### PR DESCRIPTION
**Pull request by edg-l**
Fixes #719 

## Checklist
- [ ] Linked to Github Issue
- [ ] Unit tests added
- [ ] Integration tests added.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

### CODE REVIEW

**Review by azteca1998 — APPROVED** [review]

File: src/types/nullable.rs [hunk 1]
```diff
@@ -90,46 +94,103 @@ fn snapshot_take<'ctx, 'this>(
...
+    use crate::{
+        utils::test::{jit_enum, jit_struct, load_cairo, run_program},
+        values::JitValue,
+    };
+    use pretty_assertions_sorted::assert_eq;
+
+    #[test]
+    fn test_nullable_deep_clone() {
+        let program = load_cairo! {
+            use core::array::ArrayTrait;
```
Comment (pefontana) [inline src/types/nullable.rs:168]: one question: why can we add this test as a normal cairo program?

Comment (azteca1998) [reply src/types/nullable.rs:168]: We're testing if executing this program causes a segfault or not. If it causes a segfault it'll crash the test suite and therefore make the test "fail".

The test works by forcing the invocation of the fix (by taking a snapshot of the nullable), dropping the original value and returning the snapshot. Since its value is an array, which doesn't implement Copy, it'll need to be cloned because we're destroying the original therefore freeing the array. If the value was copied and not cloned then it'd cause a double free or segfault crash.

**Review by pefontana — APPROVED** [review]
