### PR TITLE
Basic Stress Test

### LINKED ISSUE #682: Cairo Native Stress Binary
related to #282 

Implement `cairo-native-stress` binary, which loops `n` times over the following sequence:
1. Generate an unique contract. Preferably in memory.
1. Test the contract with AOT, this implies:
    1. Compile it
    1. Cache it
    1. Run it
  
The output of this binary should answer the following questions:
- how many contracts until a segmentation fault?
- how much memory a cached program occupies?

Later on, we should test optimized versions of the cache, like:
- cache with eviction
- cache with write to disk

### PR DESCRIPTION
**Pull request by JulianGCalderon**
related to #682

Adds `cairo-native-stress` that generates, compiles, caches, and runs contracts in order to stress test cairo native.
- Receives by argument the amount rounds to execute.
- In each round it generates, compiles, caches, and runs a new contract
- The compiled dynamic shared libraries are stored on disk
- The cache keeps in memory every executor for every compiled contract
- After each round, it prints a report

## Program Generation

At the start of the program, a dummy program is generated with a hardcoded value (835 in this case) in the return value:
```cairo
#[starknet::contract]
mod Contract {
    #[storage]
    struct Storage {}

    #[external(v0)]
    fn main(self: @ContractState) -> felt252 {
        return 835;
    }
}
```

At the start of each round, the program is traversed to find the hardcoded value and is replaced with a new one. This allows to generate a new valid program with a different return value each round

## Examples

With info logging (20 rounds):
image
With debug logging (5 rounds):
image

## Next Steps

- Export the logs to a JSON or a CSV and plot it
- Try different implementations of the Cache

## Checklist
- [x] Linked to Github Issue
- [x] This change requires new documentation.
  - [x] Documentation has been added/updated.

### CODE REVIEW

File: src/bin/cairo-native-stress.rs [hunk 1]
```diff
@@ -0,0 +1,325 @@
...
+const AOT_CACHE_DIR: &str = ".aot-cache";
+
+/// An unique value hardcoded into the initial contract that it's
+/// used as an anchor point to safely modify it.
+/// It can be any value as long as it's unique in the contract.
+const UNIQUE_CONTRACT_VALUE: u32 = 835;
+
+/// A stress tester for Cairo Native
+///
+/// It Sierra programs compiles with Cairo Native, caches, and executes them with AOT runner.
```
Comment (fmoletta) [inline src/bin/cairo-native-stress.rs:44]:
```suggestion
/// It compiles Sierra programs with Cairo Native, caches, and executes them with AOT runner.
```

Comment (JulianGCalderon) [reply src/bin/cairo-native-stress.rs:44]: Oh thanks, I totally missed that.

**Review by Oppen — APPROVED** [review]

**Review by edg-l — APPROVED** [review]
